version: "3"

services:

  registry:
    image: registry:latest
    container_name: registry
    ports: 
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-ui 
    ports: 
      - 8080:80
    environment: 
      - ENV_DOCKER_REGISTRY_HOST=localhost
      - ENV_DOCKER_REGISTRY_PORT=5000

volumes:
  registry-data: