# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", path: "node.sh", privileged: true

  # Managers
  (1..3).each do |number|
      config.vm.define "master#{number}" do |node|
          node.vm.network "private_network", ip: "192.168.99.20#{number}"
          node.vm.hostname = "master#{number}"
      end  
  end

  # Workers
  (1..3).each do |number|
      config.vm.define "worker#{number}" do |node|
          node.vm.network "private_network", ip: "192.168.99.21#{number}"
          node.vm.hostname = "worker#{number}"
      end  
  end

  config.vm.provider "virtualbox" do |v|
      v.memory = 2048 
      v.cpus = 1
  end

end