version: '3'

networks: 
  sample:

services:
  sample-app:
    image: sample-app
    container_name: sample-app
    
    networks: 
      - sample
    # build: .
    # environment:
    #   NODE_ENV: production
    ports:
      - 3000:3000
  sample-api:
    image: sample-api
    container_name: sample-api
    networks: 
      - sample
    ports:
      - 9090:80
  sample-mvc:
    image: sample-mvc
    container_name: sample-mvc
    networks: 
      - sample
    ports:
      - 8000:80